// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcV0-nh0i-N7HtJNO909c1VZftxJ2iZ0',
    appId: '1:93822977761:android:0aa4359af8c11ad3afd9a0',
    messagingSenderId: '93822977761',
    projectId: 'descarte-b78a4',
    storageBucket: 'descarte-b78a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0TKX5Ut_HW1cT721KLEWHY_kD1W_VQU',
    appId: '1:93822977761:ios:9cb1e7b254a11afbafd9a0',
    messagingSenderId: '93822977761',
    projectId: 'descarte-b78a4',
    storageBucket: 'descarte-b78a4.firebasestorage.app',
    androidClientId: '93822977761-1gvm6bkr1akiku6t15fkv6bbli9eu47c.apps.googleusercontent.com',
    iosClientId: '93822977761-4m8m8nurfphmru7272unok5747krnrbh.apps.googleusercontent.com',
    iosBundleId: 'br.uff.descarte.descarteBem',
  );

}